name: Invoke updateFiles on deployment managed by Cloudsoft AMP

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke updateFiles effector using curl
        env:
          AMP_PASSWORD: $
        run: |
          curl -k -u admin:${AMP_PASSWORD} -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' https://16.170.143.241/v1/applications/oapnggxmhq/entities/v022yw86pr/effectors/updateFiles
