name: Invoke updateFiles on deployment managed by Cloudsoft AMP

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke updateFiles effector using curl
#        env:
#          AMP_PASSWORD: $
        run: |
          curl -k -u admin:${{ secrets.AMP_PASSWORD }} -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' https://training-20.aws-demo.cloudsoft.io/v1/applications/yix9c5h5eq/entities/x3dp971d32/effectors/updateFiles
                                              
